# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9ztH5QuwTYeM4UtdpkCCVRDmYAC0t_M
"""

import streamlit as st

st.set_page_config(
    page_title="Welcome to SWISS PARENTERALS",
    layout="wide"
)

# -----------------  CUSTOM CSS  -----------------
st.markdown("""
    <style>
        body {
            background: linear-gradient(to right, #f5f7fa, #c3cfe2);
        }
        h1 {
            color: #2c3e50;
            text-align: center;
        }
        .big-text {
            font-size: 18px;
            color: #34495e;
            text-align: center;
        }
    </style>
""", unsafe_allow_html=True)

# ----------------- TITLE -----------------
st.markdown("<h1>👋 Welcome to <span style='color:#2980b9'>SWISS</span></h1>",
            unsafe_allow_html=True)

# ----------------- TAB LAYOUT -----------------
tabs = st.tabs([
    "Ampoule Scheduler",
    "Powder Scheduler",
    "Vendor OTIF",
    "Customer OTIF",
    "TAT Analysis",
    "Vehicle Optimisation"
])

# --- Tab 1: Ampoule Scheduler ---
with tabs[0]:
    st.markdown("### 🧪 Ampoule Scheduler")
    st.markdown("Loading module…")
    exec(open("pages/Ampoule_Scheduler.py").read())

# --- Tab 2: Powder Scheduler ---
with tabs[1]:
    st.markdown("### 🧂 Powder Scheduler")
    st.markdown("Loading module…")
    exec(open("pages/Powder_Scheduler.py").read())

# --- Tab 3: Vendor OTIF ---
with tabs[2]:
    st.markdown("### 📦 Vendor OTIF Analysis")
    st.markdown("Loading module…")
    exec(open("pages/Vendor_OTIF.py").read())

# --- Tab 4: Customer OTIF ---
with tabs[3]:
    st.markdown("### 🧑‍🤝‍🧑 Customer OTIF Analysis")
    st.markdown("Loading module…")
    exec(open("pages/Customer_OTIF.py").read())

# --- Tab 5: TAT Analysis ---
with tabs[4]:
    st.markdown("### ⏱️ TAT Analysis")
    st.markdown("Loading module…")
    exec(open("pages/TAT_Analysis.py").read())

# --- Tab 6: Vehicle Optimisation (NEW) ---
with tabs[5]:
    st.markdown("### 🚚 Vehicle Optimisation")
    st.markdown("Loading module…")
    exec(open("pages/Vehicle_Optimisation.py").read())

# ----------------- IMAGE -----------------
st.image(
    "https://images.unsplash.com/photo-1581091012184-7f03a6cc0b6e",
    use_container_width=True
)