# -*- coding: utf-8 -*-
"""Vehicle_Optimisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EBJJ7M3-S_SWpTxJwYMmlIuYx1PUSlww
"""

print('Hello')